### ISSUE TITLE
issues with serverless-offline

### ISSUE THREAD

**Issue by vanerleo** [vandium-io/vandium-serverless#1]
Not sure where to report this one.

"stackTrace":["Error: handleralready exists with name: exec","at Pipeline.add (vandium/lib/pipeline.js:73:19)","at Object.install (vandium/lib/plugins/exec/runner.js:57:14)","at wrapHandler (vandium/lib/index.js:83:18)","at Vandium (vandium/lib/index.js:151:9)","at Object.<anonymous>

**Comment by dc00p** [comment]
Looks like the serverless-offline is rerunning the vandium wrapper each time the function is invoked resulting in the function being rewrapped in vandium (double wrap), resulting in the error.

Lambda functions are designed to be configured once in the environment, whereas serverless-offline by default preserves state.

Run `serverless-offline` with the `--skipCacheInvalidation` flag.  Command should look like `sls offline start --skipCacheInvalidation` or `sls offline start -c` for short.

**Comment by dc00p** [comment]
As per your comment [vandium-io/vandium-node/issues/7](https://github.com/vandium-io/vandium-node/issues/7) I assume this issue has been resolved for you?  Let me know and I'll close it.

**Comment by vanerleo** [comment]
still was running into issues , where after a first request to the api the subsequent request would return the value of the first call
ie
api/test1
api/test2

both would return the same value depending which one was called first

so far the only work around i found

`if (process.env.SERVERLESS_STAGE == 'local') {`
`module.exports.handler = function (event, context, callback) {`
`main(event).then(function (result) {`
`_connection.end();`
`callback(null, result);`
`})`
`};`
`} else {`
`vandium.after(function () {`
`_connection.end();`
`});`
`module.exports.handler = vandium(main);`
`}`

`function main(event) {`
`//////main logic here`
`}`

what is your set up? how are you using serverless-offline

**Comment by dc00p** [comment]
As per our discussion on Gitter, I'm closing the issue.  Your resolution was to use `return _connection.end()` since it's a promise.
